//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stockmanageapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Stock_Id { get; set; }
        public string Stock_Name { get; set; }
        public string Stock_type { get; set; }
        public int Stock_qty { get; set; }
        public int Stock_preorderlevel { get; set; }
    }
}
